import type { Agent, Project } from "./types"

export const MOCK_PROJECTS: Project[] = [
	{ name: "codedeck", agentCount: 3 },
	{ name: "api-server", agentCount: 1 },
	{ name: "frontend", agentCount: 2 },
]

export const MOCK_AGENTS: Agent[] = [
	{
		id: "1",
		sessionId: "mock-session-1",
		serverId: "mock-server",
		name: "Add OAuth2 login flow",
		status: "running",
		environment: "cloud",
		project: "codedeck",
		projectSlug: "codedeck-abc12345",
		directory: "/home/user/projects/codedeck",
		branch: "agent/oauth-login",
		duration: "12m 34s",
		tokens: 45200,
		cost: 0.12,
		currentActivity: "Editing middleware.ts",
		activities: [
			{
				id: "a1",
				timestamp: "12:34",
				type: "read",
				description: "Reading auth.ts",
				detail: "src/auth/auth.ts",
			},
			{
				id: "a2",
				timestamp: "12:35",
				type: "search",
				description: 'Searching for "handler"',
				detail: "Found 12 matches in 5 files",
			},
			{
				id: "a3",
				timestamp: "12:36",
				type: "edit",
				description: "Editing middleware.ts",
				detail: "+24 -3 lines",
			},
			{
				id: "a4",
				timestamp: "12:37",
				type: "write",
				description: "Creating oauth-provider.ts",
				detail: "src/auth/oauth-provider.ts",
			},
			{
				id: "a5",
				timestamp: "12:38",
				type: "run",
				description: "Running tests",
				detail: "npm test -- --filter auth",
			},
		],
		permissions: [],
		lastActiveAt: Date.now(),
	},
	{
		id: "2",
		sessionId: "mock-session-2",
		serverId: "mock-server",
		name: "Fix CI pipeline",
		status: "running",
		environment: "local",
		project: "codedeck",
		projectSlug: "codedeck-abc12345",
		directory: "/home/user/projects/codedeck",
		branch: "agent/fix-ci",
		duration: "3m 12s",
		tokens: 12800,
		cost: 0.03,
		currentActivity: "Running tests...",
		activities: [
			{
				id: "b1",
				timestamp: "12:50",
				type: "read",
				description: "Reading .github/workflows/ci.yml",
			},
			{ id: "b2", timestamp: "12:51", type: "think", description: "Analyzing test failures" },
			{
				id: "b3",
				timestamp: "12:52",
				type: "run",
				description: "Running tests...",
				detail: "bun test",
			},
		],
		permissions: [],
		lastActiveAt: Date.now(),
	},
	{
		id: "3",
		sessionId: "mock-session-3",
		serverId: "mock-server",
		name: "Update dependencies",
		status: "completed",
		environment: "cloud",
		project: "api-server",
		projectSlug: "api-server-def67890",
		directory: "/home/user/projects/api-server",
		branch: "agent/update-deps",
		duration: "2h ago",
		tokens: 31500,
		cost: 0.08,
		activities: [
			{ id: "c1", timestamp: "11:20", type: "read", description: "Reading package.json" },
			{ id: "c2", timestamp: "11:22", type: "run", description: "Running npm outdated" },
			{
				id: "c3",
				timestamp: "11:25",
				type: "edit",
				description: "Updating package.json",
				detail: "+12 -12 lines",
			},
			{
				id: "c4",
				timestamp: "11:28",
				type: "run",
				description: "Running tests",
				detail: "All 47 tests passed",
			},
		],
		permissions: [],
		lastActiveAt: Date.now() - 2 * 60 * 60 * 1000,
	},
	{
		id: "4",
		sessionId: "mock-session-4",
		serverId: "mock-server",
		name: "Refactor database layer",
		status: "failed",
		environment: "local",
		project: "api-server",
		projectSlug: "api-server-def67890",
		directory: "/home/user/projects/api-server",
		branch: "agent/refactor-db",
		duration: "1h ago",
		tokens: 89200,
		cost: 0.24,
		currentActivity: "Failed: Out of memory",
		activities: [
			{ id: "d1", timestamp: "10:00", type: "read", description: "Reading database models" },
			{ id: "d2", timestamp: "10:05", type: "think", description: "Planning migration strategy" },
			{
				id: "d3",
				timestamp: "10:10",
				type: "edit",
				description: "Rewriting query builder",
				detail: "+245 -180 lines",
			},
		],
		permissions: [],
		lastActiveAt: Date.now() - 1 * 60 * 60 * 1000,
	},
	{
		id: "5",
		sessionId: "mock-session-5",
		serverId: "mock-server",
		name: "Add dark mode support",
		status: "waiting",
		environment: "cloud",
		project: "frontend",
		projectSlug: "frontend-aaa11111",
		directory: "/home/user/projects/frontend",
		branch: "agent/dark-mode",
		duration: "5m 10s",
		tokens: 18900,
		cost: 0.05,
		currentActivity: "Waiting for approval: install tailwind-dark-mode",
		activities: [
			{ id: "e1", timestamp: "12:40", type: "read", description: "Reading tailwind.config.ts" },
			{
				id: "e2",
				timestamp: "12:42",
				type: "tool",
				description: "Requesting permission to install package",
				detail: "tailwind-dark-mode@^2.0",
			},
		],
		permissions: [],
		lastActiveAt: Date.now(),
	},
	{
		id: "6",
		sessionId: "mock-session-6",
		serverId: "mock-server",
		name: "Implement search API",
		status: "running",
		environment: "cloud",
		project: "frontend",
		projectSlug: "frontend-aaa11111",
		directory: "/home/user/projects/frontend",
		branch: "agent/search-api",
		duration: "7m 0s",
		tokens: 22100,
		cost: 0.06,
		currentActivity: "Writing search controller",
		activities: [
			{ id: "f1", timestamp: "12:30", type: "read", description: "Reading existing API routes" },
			{
				id: "f2",
				timestamp: "12:33",
				type: "write",
				description: "Writing search controller",
				detail: "src/controllers/search.ts",
			},
		],
		permissions: [],
		lastActiveAt: Date.now(),
	},
]
