// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as WorkspaceRouteImport } from "./routes/_workspace";
import { Route as SettingsRouteImport } from "./routes/settings";
import { Route as WelcomeRouteImport } from "./routes/welcome";
import { Route as WorkspaceIndexRouteImport } from "./routes/_workspace.index";
import { Route as WorkspaceNewRouteImport } from "./routes/_workspace.new";
import { Route as WorkspaceScheduledRouteImport } from "./routes/_workspace.scheduled";
import { Route as WorkspaceUsageRouteImport } from "./routes/_workspace.usage";
import { Route as WorkspaceWorktreesRouteImport } from "./routes/_workspace.worktrees";
import { Route as SettingsIndexRouteImport } from "./routes/settings.index";
import { Route as SettingsAboutRouteImport } from "./routes/settings.about";
import { Route as SettingsAgentsRouteImport } from "./routes/settings.agents";
import { Route as SettingsAppearanceRouteImport } from "./routes/settings.appearance";
import { Route as SettingsConfigRouteImport } from "./routes/settings.config";
import { Route as SettingsConnectionsRouteImport } from "./routes/settings.connections";
import { Route as SettingsDiagnosticsRouteImport } from "./routes/settings.diagnostics";
import { Route as SettingsGeneralRouteImport } from "./routes/settings.general";
import { Route as SettingsModelsRouteImport } from "./routes/settings.models";
import { Route as SettingsNotificationsRouteImport } from "./routes/settings.notifications";
import { Route as SettingsPermissionsRouteImport } from "./routes/settings.permissions";
import { Route as SettingsProjectRouteImport } from "./routes/settings.project";
import { Route as SettingsProvidersRouteImport } from "./routes/settings.providers";
import { Route as SettingsToolsRouteImport } from "./routes/settings.tools";
import { Route as WorkspaceSessionsSessionIDRouteImport } from "./routes/_workspace.sessions.$sessionID";
import { Route as SettingsConnectionsIndexRouteImport } from "./routes/settings.connections.index";
import { Route as SettingsConnectionsLocalServiceRouteImport } from "./routes/settings.connections.local-service";
import { Route as SettingsConnectionsProfilesRouteImport } from "./routes/settings.connections.profiles";
import { Route as SettingsConnectionsWebAccessRouteImport } from "./routes/settings.connections.web-access";
import { Route as WorkspaceSessionsSessionIDChangesRouteImport } from "./routes/_workspace.sessions.$sessionID.changes";

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: "/_workspace",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any);
const WelcomeRoute = WelcomeRouteImport.update({
  id: "/welcome",
  path: "/welcome",
  getParentRoute: () => rootRouteImport,
} as any);
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => WorkspaceRoute,
} as any);
const WorkspaceNewRoute = WorkspaceNewRouteImport.update({
  id: "/new",
  path: "/new",
  getParentRoute: () => WorkspaceRoute,
} as any);
const WorkspaceScheduledRoute = WorkspaceScheduledRouteImport.update({
  id: "/scheduled",
  path: "/scheduled",
  getParentRoute: () => WorkspaceRoute,
} as any);
const WorkspaceUsageRoute = WorkspaceUsageRouteImport.update({
  id: "/usage",
  path: "/usage",
  getParentRoute: () => WorkspaceRoute,
} as any);
const WorkspaceWorktreesRoute = WorkspaceWorktreesRouteImport.update({
  id: "/worktrees",
  path: "/worktrees",
  getParentRoute: () => WorkspaceRoute,
} as any);
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => SettingsRoute,
} as any);
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => SettingsRoute,
} as any);
const SettingsAgentsRoute = SettingsAgentsRouteImport.update({
  id: "/agents",
  path: "/agents",
  getParentRoute: () => SettingsRoute,
} as any);
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: "/appearance",
  path: "/appearance",
  getParentRoute: () => SettingsRoute,
} as any);
const SettingsConfigRoute = SettingsConfigRouteImport.update({
  id: "/config",
  path: "/config",
  getParentRoute: () => SettingsRoute,
} as any);
const SettingsConnectionsRoute = SettingsConnectionsRouteImport.update({
  id: "/connections",
  path: "/connections",
  getParentRoute: () => SettingsRoute,
} as any);
const SettingsDiagnosticsRoute = SettingsDiagnosticsRouteImport.update({
  id: "/diagnostics",
  path: "/diagnostics",
  getParentRoute: () => SettingsRoute,
} as any);
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: "/general",
  path: "/general",
  getParentRoute: () => SettingsRoute,
} as any);
const SettingsModelsRoute = SettingsModelsRouteImport.update({
  id: "/models",
  path: "/models",
  getParentRoute: () => SettingsRoute,
} as any);
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: "/notifications",
  path: "/notifications",
  getParentRoute: () => SettingsRoute,
} as any);
const SettingsPermissionsRoute = SettingsPermissionsRouteImport.update({
  id: "/permissions",
  path: "/permissions",
  getParentRoute: () => SettingsRoute,
} as any);
const SettingsProjectRoute = SettingsProjectRouteImport.update({
  id: "/project",
  path: "/project",
  getParentRoute: () => SettingsRoute,
} as any);
const SettingsProvidersRoute = SettingsProvidersRouteImport.update({
  id: "/providers",
  path: "/providers",
  getParentRoute: () => SettingsRoute,
} as any);
const SettingsToolsRoute = SettingsToolsRouteImport.update({
  id: "/tools",
  path: "/tools",
  getParentRoute: () => SettingsRoute,
} as any);
const WorkspaceSessionsSessionIDRoute =
  WorkspaceSessionsSessionIDRouteImport.update({
    id: "/sessions/$sessionID",
    path: "/sessions/$sessionID",
    getParentRoute: () => WorkspaceRoute,
  } as any);
const SettingsConnectionsIndexRoute =
  SettingsConnectionsIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => SettingsConnectionsRoute,
  } as any);
const SettingsConnectionsLocalServiceRoute =
  SettingsConnectionsLocalServiceRouteImport.update({
    id: "/local-service",
    path: "/local-service",
    getParentRoute: () => SettingsConnectionsRoute,
  } as any);
const SettingsConnectionsProfilesRoute =
  SettingsConnectionsProfilesRouteImport.update({
    id: "/profiles",
    path: "/profiles",
    getParentRoute: () => SettingsConnectionsRoute,
  } as any);
const SettingsConnectionsWebAccessRoute =
  SettingsConnectionsWebAccessRouteImport.update({
    id: "/web-access",
    path: "/web-access",
    getParentRoute: () => SettingsConnectionsRoute,
  } as any);
const WorkspaceSessionsSessionIDChangesRoute =
  WorkspaceSessionsSessionIDChangesRouteImport.update({
    id: "/changes",
    path: "/changes",
    getParentRoute: () => WorkspaceSessionsSessionIDRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof WorkspaceIndexRoute;
  "/settings": typeof SettingsRouteWithChildren;
  "/welcome": typeof WelcomeRoute;
  "/new": typeof WorkspaceNewRoute;
  "/scheduled": typeof WorkspaceScheduledRoute;
  "/usage": typeof WorkspaceUsageRoute;
  "/worktrees": typeof WorkspaceWorktreesRoute;
  "/settings/about": typeof SettingsAboutRoute;
  "/settings/agents": typeof SettingsAgentsRoute;
  "/settings/appearance": typeof SettingsAppearanceRoute;
  "/settings/config": typeof SettingsConfigRoute;
  "/settings/connections": typeof SettingsConnectionsRouteWithChildren;
  "/settings/diagnostics": typeof SettingsDiagnosticsRoute;
  "/settings/general": typeof SettingsGeneralRoute;
  "/settings/models": typeof SettingsModelsRoute;
  "/settings/notifications": typeof SettingsNotificationsRoute;
  "/settings/permissions": typeof SettingsPermissionsRoute;
  "/settings/project": typeof SettingsProjectRoute;
  "/settings/providers": typeof SettingsProvidersRoute;
  "/settings/tools": typeof SettingsToolsRoute;
  "/settings/": typeof SettingsIndexRoute;
  "/sessions/$sessionID": typeof WorkspaceSessionsSessionIDRouteWithChildren;
  "/settings/connections/local-service": typeof SettingsConnectionsLocalServiceRoute;
  "/settings/connections/profiles": typeof SettingsConnectionsProfilesRoute;
  "/settings/connections/web-access": typeof SettingsConnectionsWebAccessRoute;
  "/settings/connections/": typeof SettingsConnectionsIndexRoute;
  "/sessions/$sessionID/changes": typeof WorkspaceSessionsSessionIDChangesRoute;
}
export interface FileRoutesByTo {
  "/welcome": typeof WelcomeRoute;
  "/new": typeof WorkspaceNewRoute;
  "/scheduled": typeof WorkspaceScheduledRoute;
  "/usage": typeof WorkspaceUsageRoute;
  "/worktrees": typeof WorkspaceWorktreesRoute;
  "/settings/about": typeof SettingsAboutRoute;
  "/settings/agents": typeof SettingsAgentsRoute;
  "/settings/appearance": typeof SettingsAppearanceRoute;
  "/settings/config": typeof SettingsConfigRoute;
  "/settings/diagnostics": typeof SettingsDiagnosticsRoute;
  "/settings/general": typeof SettingsGeneralRoute;
  "/settings/models": typeof SettingsModelsRoute;
  "/settings/notifications": typeof SettingsNotificationsRoute;
  "/settings/permissions": typeof SettingsPermissionsRoute;
  "/settings/project": typeof SettingsProjectRoute;
  "/settings/providers": typeof SettingsProvidersRoute;
  "/settings/tools": typeof SettingsToolsRoute;
  "/": typeof WorkspaceIndexRoute;
  "/settings": typeof SettingsIndexRoute;
  "/sessions/$sessionID": typeof WorkspaceSessionsSessionIDRouteWithChildren;
  "/settings/connections/local-service": typeof SettingsConnectionsLocalServiceRoute;
  "/settings/connections/profiles": typeof SettingsConnectionsProfilesRoute;
  "/settings/connections/web-access": typeof SettingsConnectionsWebAccessRoute;
  "/settings/connections": typeof SettingsConnectionsIndexRoute;
  "/sessions/$sessionID/changes": typeof WorkspaceSessionsSessionIDChangesRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_workspace": typeof WorkspaceRouteWithChildren;
  "/settings": typeof SettingsRouteWithChildren;
  "/welcome": typeof WelcomeRoute;
  "/_workspace/new": typeof WorkspaceNewRoute;
  "/_workspace/scheduled": typeof WorkspaceScheduledRoute;
  "/_workspace/usage": typeof WorkspaceUsageRoute;
  "/_workspace/worktrees": typeof WorkspaceWorktreesRoute;
  "/settings/about": typeof SettingsAboutRoute;
  "/settings/agents": typeof SettingsAgentsRoute;
  "/settings/appearance": typeof SettingsAppearanceRoute;
  "/settings/config": typeof SettingsConfigRoute;
  "/settings/connections": typeof SettingsConnectionsRouteWithChildren;
  "/settings/diagnostics": typeof SettingsDiagnosticsRoute;
  "/settings/general": typeof SettingsGeneralRoute;
  "/settings/models": typeof SettingsModelsRoute;
  "/settings/notifications": typeof SettingsNotificationsRoute;
  "/settings/permissions": typeof SettingsPermissionsRoute;
  "/settings/project": typeof SettingsProjectRoute;
  "/settings/providers": typeof SettingsProvidersRoute;
  "/settings/tools": typeof SettingsToolsRoute;
  "/_workspace/": typeof WorkspaceIndexRoute;
  "/settings/": typeof SettingsIndexRoute;
  "/_workspace/sessions/$sessionID": typeof WorkspaceSessionsSessionIDRouteWithChildren;
  "/settings/connections/local-service": typeof SettingsConnectionsLocalServiceRoute;
  "/settings/connections/profiles": typeof SettingsConnectionsProfilesRoute;
  "/settings/connections/web-access": typeof SettingsConnectionsWebAccessRoute;
  "/settings/connections/": typeof SettingsConnectionsIndexRoute;
  "/_workspace/sessions/$sessionID/changes": typeof WorkspaceSessionsSessionIDChangesRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/settings"
    | "/welcome"
    | "/new"
    | "/scheduled"
    | "/usage"
    | "/worktrees"
    | "/settings/about"
    | "/settings/agents"
    | "/settings/appearance"
    | "/settings/config"
    | "/settings/connections"
    | "/settings/diagnostics"
    | "/settings/general"
    | "/settings/models"
    | "/settings/notifications"
    | "/settings/permissions"
    | "/settings/project"
    | "/settings/providers"
    | "/settings/tools"
    | "/settings/"
    | "/sessions/$sessionID"
    | "/settings/connections/local-service"
    | "/settings/connections/profiles"
    | "/settings/connections/web-access"
    | "/settings/connections/"
    | "/sessions/$sessionID/changes";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/welcome"
    | "/new"
    | "/scheduled"
    | "/usage"
    | "/worktrees"
    | "/settings/about"
    | "/settings/agents"
    | "/settings/appearance"
    | "/settings/config"
    | "/settings/diagnostics"
    | "/settings/general"
    | "/settings/models"
    | "/settings/notifications"
    | "/settings/permissions"
    | "/settings/project"
    | "/settings/providers"
    | "/settings/tools"
    | "/"
    | "/settings"
    | "/sessions/$sessionID"
    | "/settings/connections/local-service"
    | "/settings/connections/profiles"
    | "/settings/connections/web-access"
    | "/settings/connections"
    | "/sessions/$sessionID/changes";
  id:
    | "__root__"
    | "/_workspace"
    | "/settings"
    | "/welcome"
    | "/_workspace/new"
    | "/_workspace/scheduled"
    | "/_workspace/usage"
    | "/_workspace/worktrees"
    | "/settings/about"
    | "/settings/agents"
    | "/settings/appearance"
    | "/settings/config"
    | "/settings/connections"
    | "/settings/diagnostics"
    | "/settings/general"
    | "/settings/models"
    | "/settings/notifications"
    | "/settings/permissions"
    | "/settings/project"
    | "/settings/providers"
    | "/settings/tools"
    | "/_workspace/"
    | "/settings/"
    | "/_workspace/sessions/$sessionID"
    | "/settings/connections/local-service"
    | "/settings/connections/profiles"
    | "/settings/connections/web-access"
    | "/settings/connections/"
    | "/_workspace/sessions/$sessionID/changes";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  WorkspaceRoute: typeof WorkspaceRouteWithChildren;
  SettingsRoute: typeof SettingsRouteWithChildren;
  WelcomeRoute: typeof WelcomeRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_workspace": {
      id: "/_workspace";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof WorkspaceRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof SettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/welcome": {
      id: "/welcome";
      path: "/welcome";
      fullPath: "/welcome";
      preLoaderRoute: typeof WelcomeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_workspace/": {
      id: "/_workspace/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof WorkspaceIndexRouteImport;
      parentRoute: typeof WorkspaceRoute;
    };
    "/_workspace/new": {
      id: "/_workspace/new";
      path: "/new";
      fullPath: "/new";
      preLoaderRoute: typeof WorkspaceNewRouteImport;
      parentRoute: typeof WorkspaceRoute;
    };
    "/_workspace/scheduled": {
      id: "/_workspace/scheduled";
      path: "/scheduled";
      fullPath: "/scheduled";
      preLoaderRoute: typeof WorkspaceScheduledRouteImport;
      parentRoute: typeof WorkspaceRoute;
    };
    "/_workspace/usage": {
      id: "/_workspace/usage";
      path: "/usage";
      fullPath: "/usage";
      preLoaderRoute: typeof WorkspaceUsageRouteImport;
      parentRoute: typeof WorkspaceRoute;
    };
    "/_workspace/worktrees": {
      id: "/_workspace/worktrees";
      path: "/worktrees";
      fullPath: "/worktrees";
      preLoaderRoute: typeof WorkspaceWorktreesRouteImport;
      parentRoute: typeof WorkspaceRoute;
    };
    "/settings/": {
      id: "/settings/";
      path: "/";
      fullPath: "/settings/";
      preLoaderRoute: typeof SettingsIndexRouteImport;
      parentRoute: typeof SettingsRoute;
    };
    "/settings/about": {
      id: "/settings/about";
      path: "/about";
      fullPath: "/settings/about";
      preLoaderRoute: typeof SettingsAboutRouteImport;
      parentRoute: typeof SettingsRoute;
    };
    "/settings/agents": {
      id: "/settings/agents";
      path: "/agents";
      fullPath: "/settings/agents";
      preLoaderRoute: typeof SettingsAgentsRouteImport;
      parentRoute: typeof SettingsRoute;
    };
    "/settings/appearance": {
      id: "/settings/appearance";
      path: "/appearance";
      fullPath: "/settings/appearance";
      preLoaderRoute: typeof SettingsAppearanceRouteImport;
      parentRoute: typeof SettingsRoute;
    };
    "/settings/config": {
      id: "/settings/config";
      path: "/config";
      fullPath: "/settings/config";
      preLoaderRoute: typeof SettingsConfigRouteImport;
      parentRoute: typeof SettingsRoute;
    };
    "/settings/connections": {
      id: "/settings/connections";
      path: "/connections";
      fullPath: "/settings/connections";
      preLoaderRoute: typeof SettingsConnectionsRouteImport;
      parentRoute: typeof SettingsRoute;
    };
    "/settings/diagnostics": {
      id: "/settings/diagnostics";
      path: "/diagnostics";
      fullPath: "/settings/diagnostics";
      preLoaderRoute: typeof SettingsDiagnosticsRouteImport;
      parentRoute: typeof SettingsRoute;
    };
    "/settings/general": {
      id: "/settings/general";
      path: "/general";
      fullPath: "/settings/general";
      preLoaderRoute: typeof SettingsGeneralRouteImport;
      parentRoute: typeof SettingsRoute;
    };
    "/settings/models": {
      id: "/settings/models";
      path: "/models";
      fullPath: "/settings/models";
      preLoaderRoute: typeof SettingsModelsRouteImport;
      parentRoute: typeof SettingsRoute;
    };
    "/settings/notifications": {
      id: "/settings/notifications";
      path: "/notifications";
      fullPath: "/settings/notifications";
      preLoaderRoute: typeof SettingsNotificationsRouteImport;
      parentRoute: typeof SettingsRoute;
    };
    "/settings/permissions": {
      id: "/settings/permissions";
      path: "/permissions";
      fullPath: "/settings/permissions";
      preLoaderRoute: typeof SettingsPermissionsRouteImport;
      parentRoute: typeof SettingsRoute;
    };
    "/settings/project": {
      id: "/settings/project";
      path: "/project";
      fullPath: "/settings/project";
      preLoaderRoute: typeof SettingsProjectRouteImport;
      parentRoute: typeof SettingsRoute;
    };
    "/settings/providers": {
      id: "/settings/providers";
      path: "/providers";
      fullPath: "/settings/providers";
      preLoaderRoute: typeof SettingsProvidersRouteImport;
      parentRoute: typeof SettingsRoute;
    };
    "/settings/tools": {
      id: "/settings/tools";
      path: "/tools";
      fullPath: "/settings/tools";
      preLoaderRoute: typeof SettingsToolsRouteImport;
      parentRoute: typeof SettingsRoute;
    };
    "/_workspace/sessions/$sessionID": {
      id: "/_workspace/sessions/$sessionID";
      path: "/sessions/$sessionID";
      fullPath: "/sessions/$sessionID";
      preLoaderRoute: typeof WorkspaceSessionsSessionIDRouteImport;
      parentRoute: typeof WorkspaceRoute;
    };
    "/settings/connections/": {
      id: "/settings/connections/";
      path: "/";
      fullPath: "/settings/connections/";
      preLoaderRoute: typeof SettingsConnectionsIndexRouteImport;
      parentRoute: typeof SettingsConnectionsRoute;
    };
    "/settings/connections/local-service": {
      id: "/settings/connections/local-service";
      path: "/local-service";
      fullPath: "/settings/connections/local-service";
      preLoaderRoute: typeof SettingsConnectionsLocalServiceRouteImport;
      parentRoute: typeof SettingsConnectionsRoute;
    };
    "/settings/connections/profiles": {
      id: "/settings/connections/profiles";
      path: "/profiles";
      fullPath: "/settings/connections/profiles";
      preLoaderRoute: typeof SettingsConnectionsProfilesRouteImport;
      parentRoute: typeof SettingsConnectionsRoute;
    };
    "/settings/connections/web-access": {
      id: "/settings/connections/web-access";
      path: "/web-access";
      fullPath: "/settings/connections/web-access";
      preLoaderRoute: typeof SettingsConnectionsWebAccessRouteImport;
      parentRoute: typeof SettingsConnectionsRoute;
    };
    "/_workspace/sessions/$sessionID/changes": {
      id: "/_workspace/sessions/$sessionID/changes";
      path: "/changes";
      fullPath: "/sessions/$sessionID/changes";
      preLoaderRoute: typeof WorkspaceSessionsSessionIDChangesRouteImport;
      parentRoute: typeof WorkspaceSessionsSessionIDRoute;
    };
  }
}

interface WorkspaceSessionsSessionIDRouteChildren {
  WorkspaceSessionsSessionIDChangesRoute: typeof WorkspaceSessionsSessionIDChangesRoute;
}

const WorkspaceSessionsSessionIDRouteChildren: WorkspaceSessionsSessionIDRouteChildren =
  {
    WorkspaceSessionsSessionIDChangesRoute:
      WorkspaceSessionsSessionIDChangesRoute,
  };

const WorkspaceSessionsSessionIDRouteWithChildren =
  WorkspaceSessionsSessionIDRoute._addFileChildren(
    WorkspaceSessionsSessionIDRouteChildren,
  );

interface WorkspaceRouteChildren {
  WorkspaceNewRoute: typeof WorkspaceNewRoute;
  WorkspaceScheduledRoute: typeof WorkspaceScheduledRoute;
  WorkspaceUsageRoute: typeof WorkspaceUsageRoute;
  WorkspaceWorktreesRoute: typeof WorkspaceWorktreesRoute;
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute;
  WorkspaceSessionsSessionIDRoute: typeof WorkspaceSessionsSessionIDRouteWithChildren;
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceNewRoute: WorkspaceNewRoute,
  WorkspaceScheduledRoute: WorkspaceScheduledRoute,
  WorkspaceUsageRoute: WorkspaceUsageRoute,
  WorkspaceWorktreesRoute: WorkspaceWorktreesRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
  WorkspaceSessionsSessionIDRoute: WorkspaceSessionsSessionIDRouteWithChildren,
};

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
);

interface SettingsConnectionsRouteChildren {
  SettingsConnectionsLocalServiceRoute: typeof SettingsConnectionsLocalServiceRoute;
  SettingsConnectionsProfilesRoute: typeof SettingsConnectionsProfilesRoute;
  SettingsConnectionsWebAccessRoute: typeof SettingsConnectionsWebAccessRoute;
  SettingsConnectionsIndexRoute: typeof SettingsConnectionsIndexRoute;
}

const SettingsConnectionsRouteChildren: SettingsConnectionsRouteChildren = {
  SettingsConnectionsLocalServiceRoute: SettingsConnectionsLocalServiceRoute,
  SettingsConnectionsProfilesRoute: SettingsConnectionsProfilesRoute,
  SettingsConnectionsWebAccessRoute: SettingsConnectionsWebAccessRoute,
  SettingsConnectionsIndexRoute: SettingsConnectionsIndexRoute,
};

const SettingsConnectionsRouteWithChildren =
  SettingsConnectionsRoute._addFileChildren(SettingsConnectionsRouteChildren);

interface SettingsRouteChildren {
  SettingsAboutRoute: typeof SettingsAboutRoute;
  SettingsAgentsRoute: typeof SettingsAgentsRoute;
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute;
  SettingsConfigRoute: typeof SettingsConfigRoute;
  SettingsConnectionsRoute: typeof SettingsConnectionsRouteWithChildren;
  SettingsDiagnosticsRoute: typeof SettingsDiagnosticsRoute;
  SettingsGeneralRoute: typeof SettingsGeneralRoute;
  SettingsModelsRoute: typeof SettingsModelsRoute;
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute;
  SettingsPermissionsRoute: typeof SettingsPermissionsRoute;
  SettingsProjectRoute: typeof SettingsProjectRoute;
  SettingsProvidersRoute: typeof SettingsProvidersRoute;
  SettingsToolsRoute: typeof SettingsToolsRoute;
  SettingsIndexRoute: typeof SettingsIndexRoute;
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsAgentsRoute: SettingsAgentsRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsConfigRoute: SettingsConfigRoute,
  SettingsConnectionsRoute: SettingsConnectionsRouteWithChildren,
  SettingsDiagnosticsRoute: SettingsDiagnosticsRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsModelsRoute: SettingsModelsRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsPermissionsRoute: SettingsPermissionsRoute,
  SettingsProjectRoute: SettingsProjectRoute,
  SettingsProvidersRoute: SettingsProvidersRoute,
  SettingsToolsRoute: SettingsToolsRoute,
  SettingsIndexRoute: SettingsIndexRoute,
};

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  WorkspaceRoute: WorkspaceRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  WelcomeRoute: WelcomeRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
